import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// invece di utilizzare il tag head utilizziamo questo formato per inserie i metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
